name: gfriedri-em-alignment-flows
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jaxlib=*=*cuda*
  - jax
  - nvidia::cuda-nvcc
  - pip
  - pip:
     - psutil
     - tensorflow
     - tensorstore
     - git+https://github.com/fmi-basel/gfriedri-em-alignment@v0.2.4
     - prefect==2.10.*
     - git+https://github.com/fmi-faim/custom-prefect-result@v0.1.7
     - git+https://github.com/fmi-faim/faim-prefect@v0.2.2
